"""Default watch topics / importance factors for alert scoring."""

DEFAULT_IMPORTANCE_FACTORS: list[dict] = [
    {
        "name": "pricing_and_offers",
        "description": "Price cuts, new prices, sales, discounts, and promotional offers",
        "weight": 1.35,
        "keywords": [
            "price",
            "pricing",
            "new price",
            "sale",
            "offer",
            "discount",
            "promo",
            "promotion",
            "deal",
            "limited time",
            "percent off",
            "% off",
            "save",
            "free trial",
            "introductory",
            "launch price",
            "from $",
            "/month",
            "/mo",
            "per user",
            "per seat",
            "billed",
            "cheaper",
            "lower price",
            "price drop",
            "markdown",
            "coupon",
            "black friday",
            "cyber monday",
        ],
    },
    {
        "name": "plans_and_packaging",
        "description": "Plan renames, new tiers, free/pro/business/enterprise packaging",
        "weight": 1.2,
        "keywords": [
            "plan",
            "tier",
            "package",
            "packaging",
            "free",
            "starter",
            "basic",
            "plus",
            "pro",
            "business",
            "team",
            "enterprise",
            "unlimited",
            "seats",
            "usage-based",
            "seat-based",
            "contact sales",
            "custom pricing",
        ],
    },
    {
        "name": "ai_and_automation",
        "description": "AI assistants, agents, copilots, automation launches",
        "weight": 1.25,
        "keywords": [
            "AI",
            "artificial intelligence",
            "copilot",
            "assistant",
            "agent",
            "agents",
            "llm",
            "gpt",
            "automation",
            "autonomous",
            "Notion AI",
            "Linear Agent",
            "machine learning",
        ],
    },
    {
        "name": "product_launches",
        "description": "New features, launches, now available, beta/GA",
        "weight": 1.15,
        "keywords": [
            "launch",
            "launched",
            "introducing",
            "announcing",
            "now available",
            "new feature",
            "release",
            "released",
            "beta",
            "general availability",
            "GA",
            "early access",
            "preview",
            "shipped",
            "rollout",
        ],
    },
    {
        "name": "security_and_enterprise",
        "description": "SSO, SAML, compliance, security, admin controls",
        "weight": 1.1,
        "keywords": [
            "SSO",
            "SAML",
            "SCIM",
            "SOC 2",
            "SOC2",
            "GDPR",
            "HIPAA",
            "security",
            "compliance",
            "admin",
            "audit log",
            "RBAC",
            "permissions",
            "encryption",
        ],
    },
    {
        "name": "integrations_and_platform",
        "description": "API, integrations, marketplace, platform partnerships",
        "weight": 1.0,
        "keywords": [
            "API",
            "integration",
            "integrations",
            "webhook",
            "marketplace",
            "connector",
            "plugin",
            "SDK",
            "platform",
            "partner",
            "Zapier",
            "Slack",
        ],
    },
]
